version: "3.8"

services:
  ubuntu:
    build:
      context: ./
      dockerfile: ./ubuntu/Dockerfile
    volumes:
      - ./../:/root/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    tty: true
