version: "3.8"

services:
  ubuntu:
    build:
      context: .
      dockerfile: ubuntu/Dockerfile
    platform: linux/amd64
    volumes:
      - ..:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    tty: true
